obs:
  - path: D:\http-rest-api
    commands:
      - go build -o ./build/bin/app1.go cmd/apiserver/main.go
      - go build -o ./build/bin/app1.go cmd/apiserver/main.go
  - path: D:\app_todo
    commands:
      - go build -o ./build/bin/app1.go

db:
  username: "postgres"
  host: "localhost"
  port: "5438"
  dbname: "postgres"
  sslmode: "disable"